name: dask-gpu
version: 0.0.1
appVersion: 0.17.1
description: Distributed computation in Python with task scheduling
home: https://dask.pydata.org
icon: https://avatars3.githubusercontent.com/u/17131925?v=3&s=200
sources:
- https://github.com/dask/dask
maintainers:
- name: msalvaris
  email: salvaris@gmail.com


